repos:
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-xml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
